version: 0.2


env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - eval \$($(brew --prefix)/bin/brew shellenv)
      - brew tap aws/tap
      - brew install aws-sam-cli
  build:
    commands:
      - make deps
      - make build
  post_build:
    commands:
      - make package
      - make deploy
      - make publish
