version: 0.2


env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - make deps
      - make build
  post_build:
    commands:
      - make package
      - make deploy
      - make publish
